### ISSUE TITLE
Change character encoding

### ISSUE THREAD

**Issue by ssr-yuki** [YukiOrigane/RobotControlExperiment#32]
全ファイルのエンコードを，現状のShift-JISからUTF-8に変更したい．
これにより，主にLinux環境への導入が容易になる．

MATLAB 2020a以降では全てのプラットホーム(OS)においてUTF-8のフォーマットがサポートされているため，最新版を利用する限り問題は生じ得ないと考えられる．

**Comment by YukiOrigane** [comment]
UTF-8への移行，問題ないと思います．
一応，変更後のタイミングで，2020a以降を利用するようにSlackへの通知と，wikiやREADMEに記載しましょう

**Comment by ssr-yuki** [comment]
ありがとうございます．
そしたらこちら，私の方でPR投げる形でよろしいですかね？

**Comment by YukiOrigane** [comment]
問題ありません。よろしくお願いします。
